application: bikegears-hrd
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /admin.*
  script: bgadmin.py
  login: admin
- url: /user.*
  script: bikegears.py
  login: required
- url: /
  script: welcome.py