application: bikegears-hrd
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /admin.*
  script: bgadmin.app
  login: admin
- url: /user.*
  script: bikegears.app
  login: required
- url: /
  script: welcome.app
  
libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"